import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/Header/HeaderWeather';
import Footer from '@/components/Footer/FooterWeather';

export const metadata: Metadata = {
  title: 'Weather',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
